# Generated by Django 2.0.4 on 2018-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='polarity',
            field=models.BooleanField(default=False),
        ),
    ]
