# Generated by Django 2.0.4 on 2018-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_reviews_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='intensity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='intensity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
