# Generated by Django 2.0.6 on 2018-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20180609_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='data',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='diseasetype',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='hospital',
        ),
        migrations.AddField(
            model_name='disease',
            name='diseaseName',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='disease',
            name='diseaseType',
            field=models.CharField(default='', max_length=5000, unique=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='severity',
            field=models.IntegerField(default=5),
        ),
    ]
